# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Estimate Transfer Entropy.
#'
#' \code{ComputeTE} return estimation of transfer entropy between two random process given a method.
#'
#' A function to calculate Transfer entropy from a random process \code{Y} to 
#' the random process \code{X} with specified \code{embedding} dimension and \code{k}'th neighbor for 
#' k nearest neibor search used in the estimation given a \code{method} from provided methods in this package.
#' TODO: fix details (talk about adding noise somewhere)
#'
#' @param X Numeric vector, Transfer Entropy is calculated to random process X 
#' @param Y Numeric vector, Transfer Entropy is calculated from random process Y
#' @param embedding Numeric, The embedding dimension. It should be positive
#' @param k Numeric, The k'th neighbor. It should be positive
#' @param method String, The method to be used to estimate TE from ("MI_dif","Direct","Correlation")
#' @param epsDistace Numeric, The distance used for measuring TE in Correlation method, by default it is the average distance calculated in XKY
#' @return Numeric, The estimated transfer entropy
#' 
#' @family TODO arbitrary
#' @seealso TODO arbitrary
#' @aliases te transferentropy transfer-entropy
#' 
##TODO @examples 
ComputeTE <- function(X, Y, embedding, k, method="MI_diff", epsDist=-1) {
  methods = c("correlation","mi_diff")
  method = charmatch(tolower(method),methods)
  if (is.na(method) )
    stop("Method not specified correctly. Please choose one of the following. (\"MI_diff\", \"Correlation\")")
#Other parameter check:
  if( embedding%%1 != 0 || embedding <= 0 )
	  stop("Embedding should be greater than zero")
  if( embedding > sqrt(length(X)) )
    warning("Embedding is big may not be sensible")
  if( k%%1 != 0 || k <= 0 )
	  stop("k (neighbor) should be greater than zero")
  if( k > sqrt(length(X)) )
    warning("k is big may not be sensible")
  if( length(X) != length(Y))
    stop("X and Y should have the same length")
  
  .Call('Rcpp_ComputeTE', X, Y, embedding, k, methods[method], epsDist, PACKAGE = 'ComputeTE')
}
